### ISSUE TITLE
Not all dependencies listed in composer.json

### ISSUE THREAD

**Issue by cbergau** [iwalz/zendserverapi#44]
When i am installing the zendserverapi and try to run the unit test i figured out, that there are some zend packages missing in the composer.json file.

**Comment by cbergau** [comment]
Example Zend\Uri\Http

**Comment by iwalz** [comment]
Hmm, Zend\Uri is a dependency of Zend\Http: https://github.com/zendframework/zf2/blob/master/library/Zend/Http/composer.json

Can you delete your vendor directory,your composer.lock and run install again? Do you have the zend packagist repo registered?

**Comment by iwalz** [comment]
The travis builds are fine, that's a complete new install from scratch, without ZF2 somewhere.
So it's either a local or an autoloader issue. Is the zend-uri inside the vendor directory? 
Do you maybe have an old composer.lock from a previous installation locally? 
Can you provide me the output of <code>composer.phar show --self</code>? 
Alternativly, you can rebuild the autoloader by running <code>composer.phar dump-autoload</code>.

Hope that solves your issue. The .travis.yml might be a good place to figure out how to run the test suite.

**Comment by iwalz** [comment]
For one or another reason, the dependencies are not fetched recursivly by composer.
Happened on Ubuntu 12.10, VirtualBox environment, company network, with a single composer.phar. Need to investigate with @cbergau 
Was a git clone of the master, want to check the client side install via composer

**Comment by iwalz** [comment]
Could be closed as it seem to be related to a known composer issue: http://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md

ping @weierophinney cause it's happening on the zend packagist repo.

The installation was fine and exactly what I do in travis. For one or another reason, none recursive dependecy was fetched. But composer show on zendframework/zend-http listed the dependencies. I can not reproduce it on one of my machines (or whatever it's related to) - 2 colleagues of mine can reproduce it all the time. Installing the whole framework helps, but it should not be the solution I guess ...
